# Generated by Django 4.0 on 2021-12-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_url',
            new_name='url',
        ),
    ]
