# Generated by Django 4.0 on 2021-12-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_url',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
