# Generated by Django 4.0 on 2021-12-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_category_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_url',
            new_name='url',
        ),
    ]
