# Generated by Django 4.0 on 2022-01-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_category_url_category_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
